#!/bin/bash
checkfixed=0
fixedentries="NA"
entries=0
noobsoleteparam=""
for arg in "$@"
do
    if [ "$arg" == "--fixed" ] || [ "$arg" == "-f" ]
    then
        checkfixed="1"
    fi

    if [ "$arg" == "--no-obsolete" ] || [ "$arg" == "-o" ]
    then
        noobsoleteparam=" --no-obsolete "
    fi
done


if [ "${checkfixed}" == "1" ] ; then
  fixedentries=$(
    debsecan \
    --only-fixed ${noobsoleteparam} \
    --suite=$(lsb_release -c|sed -e "s|.*[[:space:]]||g")  |wc -l)
fi
entries=$(
  debsecan ${noobsoleteparam} \
  --suite=$(lsb_release -c|sed -e "s|.*[[:space:]]||g") | wc -l)


if [ "${entries}" != "0" ] ; then
  echo "Affected by ${entries} CVEs"
  if [ "${fixedentries}" != "NA" ] ; then
    echo "!!! ${fixedentries} CVEs have been fixed already !!!"
  fi
  exit 1
fi
exit 0
